### ISSUE TITLE
'get_value' function missing in GTFS-All2Utrecht.py

### ISSUE THREAD

**Issue by ghost** [lmeulen/GTFS-Visuals#1]
I am trying to run the script _GTFS-All2Utrecht.py_ and could not find the function _get_value_ around line 52. Am I missing anything?

**Comment by lmeulen** [comment]
Thanks for the feedback. You are right, it is missing. It is a generic function I use for accessing JSON structures. 

x = {
  "name": "John",
  "age": 30,
  "city": "New York",
  "address" : {
      "street": "Avenue",
      "number": 9
  }
}

def get_value(obj, lvl1, lvl2=None):
    res = None;
    if obj and (lvl1 in obj):
        res =  obj[lvl1]
        if res and lvl2:
            if (lvl2 in res):
                res = res[lvl2]
            else:
                res = None
    return res

print(get_value(x, 'name',))
print(get_value(x, 'address', 'street'))

I will add it to the source file.
